CREATE TABLE "MESSAGES" (
ACCOUNT_ID  VARCHAR COLUMN_ENCODING 'PREFIX_ENCODING' COMPRESSION 'LZ4' COMMENT 'Hash partition for the account',
DATE_SENT TIMESTAMP COMMENT 'Date the message was sent',
MESSAGE_ID VARCHAR COLUMN_ENCODING 'PREFIX_ENCODING' COMPRESSION 'LZ4' COMMENT 'Unique id for the message',
STATUS  VARCHAR COLUMN_ENCODING 'DICT_ENCODING' COMMENT 'State machine for the message',
PRIMARY KEY (ACCOUNT_ID, DATE_SENT, MESSAGE_ID))
PARTITION BY HASH(ACCOUNT_ID) PARTITIONS 32 NUM_REPLICAS 3;

CREATE TABLE "ACCOUNTS" (
ACCOUNT_ID  VARCHAR COLUMN_ENCODING 'PREFIX_ENCODING' COMPRESSION 'LZ4' COMMENT 'Unique ID for the account',
ACCOUNT_NAME VARCHAR COMMENT 'Friendly name for the account',
PRIMARY KEY(ACCOUNT_ID))
PARTITION BY HASH(ACCOUNT_ID) PARTITIONS 2 NUM_REPLICAS 3;

INSERT INTO "ACCOUNTS" VALUES ('1', 'Test Account 1');
INSERT INTO "ACCOUNTS" VALUES ('2', 'Test Account 2');

INSERT INTO "MESSAGES" VALUES ('1', '2020-02-01 00:00:00', '1', 'DELIVERED');
INSERT INTO "MESSAGES" VALUES ('1', '2020-02-01 10:00:00', '2', 'UNDELIVERED');

INSERT INTO "MESSAGES" VALUES ('2', '2020-02-13 00:00:00', '1', 'DELIVERED');
INSERT INTO "MESSAGES" VALUES ('2', '2020-02-12 10:00:00', '2', 'DELIVERED');
!commit

SELECT * FROM "MESSAGES" as msg LEFT JOIN "ACCOUNTS" as "a" ON a.ACCOUNT_ID = msg.ACCOUNT_ID;
